#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
BUILD_DIR="$REPO_DIR/build"
REPO_SLUG="ppet36/ArduinoEditor"
BRANCH="main"
DRY_RUN=0
TEMP_DIR=""

die() {
    echo "ERROR: $*" >&2
    exit 1
}

step() {
    echo
    echo "==> $*"
}

usage() {
    cat <<'EOF'
Usage: scripts/publish-release.sh [--dry-run]

Create an annotated version tag and a draft GitHub Release from artifacts
produced by scripts/build-release.sh. Release notes are generated by Codex.

  --dry-run  Validate the release and generate notes/checksums without
             creating a tag or changing anything on GitHub.
EOF
}

require_command() {
    command -v "$1" >/dev/null 2>&1 || die "Required command not found: $1"
}

require_file() {
    [ -s "$1" ] || die "Expected artifact is missing or empty: $1"
}

file_size() {
    if stat -f '%z' "$1" >/dev/null 2>&1; then
        stat -f '%z' "$1"
    else
        stat -c '%s' "$1"
    fi
}

cleanup() {
    status=$?
    trap - EXIT INT TERM
    if [ -n "$TEMP_DIR" ] && [ -d "$TEMP_DIR" ]; then
        rm -rf "$TEMP_DIR"
    fi
    exit "$status"
}

trap cleanup EXIT INT TERM

while [ "$#" -gt 0 ]; do
    case "$1" in
        --dry-run)
            DRY_RUN=1
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            usage >&2
            die "Unknown argument: $1"
            ;;
    esac
    shift
done

cd "$REPO_DIR"

step "Preflight"
for command_name in codex gh git jq sed shasum stat; do
    require_command "$command_name"
done

[ "$(git branch --show-current)" = "$BRANCH" ] || die "The local branch must be $BRANCH"
[ -z "$(git status --porcelain --untracked-files=all)" ] || die "The local working tree is not clean"

git fetch origin "$BRANCH"
COMMIT="$(git rev-parse HEAD)"
[ "$COMMIT" = "$(git rev-parse "origin/$BRANCH")" ] || die "Local HEAD does not match origin/$BRANCH"

gh auth status -h github.com >/dev/null || die "GitHub CLI is not authenticated; run: gh auth login -h github.com"
codex login status >/dev/null || die "Codex CLI is not authenticated; run: codex login"

VERSION="$(sed -n 's/^AE_VERSION[[:space:]]*:=[[:space:]]*//p' "$BUILD_DIR/version.mk")"
[[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || die "Invalid AE_VERSION in build/version.mk: $VERSION"
TAG="v$VERSION"
TITLE="Arduino Editor $VERSION"

PREVIOUS_TAG=""
while IFS= read -r candidate; do
    if [ "$candidate" != "$TAG" ] && [[ "$candidate" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        PREVIOUS_TAG="$candidate"
        break
    fi
done < <(git tag --merged HEAD --sort=-version:refname)
[ -n "$PREVIOUS_TAG" ] || die "No previous version tag was found"
[ -n "$(git log --format='%H' "$PREVIOUS_TAG..HEAD")" ] || die "There are no commits since $PREVIOUS_TAG"

ARTIFACT_NAMES=(
    "ArduinoEditor-$VERSION-macos.pkg"
    "ArduinoEditorSetup-x86_64-$VERSION.exe"
    "ArduinoEditor-Windows-x86_64-$VERSION.zip"
    "ArduinoEditor-Linux-x86_64-$VERSION.AppImage"
    "ArduinoEditor-rpi-aarch64-$VERSION.AppImage"
    "arduino-editor_rpi_arm64_$VERSION.deb"
)
ARTIFACTS=()
for name in "${ARTIFACT_NAMES[@]}"; do
    path="$BUILD_DIR/$name"
    require_file "$path"
    ARTIFACTS+=("$path")
done

if git rev-parse --verify --quiet "refs/tags/$TAG" >/dev/null; then
    [ "$(git rev-list -n 1 "$TAG")" = "$COMMIT" ] || die "Local tag $TAG points to a different commit"
fi

REMOTE_TAG_OUTPUT="$(git ls-remote --tags origin "refs/tags/$TAG" "refs/tags/$TAG^{}")"
REMOTE_TAG_COMMIT="$(printf '%s\n' "$REMOTE_TAG_OUTPUT" | sed -n 's/[[:space:]]refs\/tags\/.*\^{}$//p' | head -n 1)"
if [ -z "$REMOTE_TAG_COMMIT" ]; then
    REMOTE_TAG_COMMIT="$(printf '%s\n' "$REMOTE_TAG_OUTPUT" | sed -n 's/[[:space:]]refs\/tags\/.*$//p' | head -n 1)"
fi
if [ -n "$REMOTE_TAG_COMMIT" ] && [ "$REMOTE_TAG_COMMIT" != "$COMMIT" ]; then
    die "Remote tag $TAG points to a different commit"
fi

RELEASE_JSON="$(gh api "repos/$REPO_SLUG/releases?per_page=100" | \
    jq -c --arg tag "$TAG" 'map(select(.tag_name == $tag))[0] // empty')"
if [ -n "$RELEASE_JSON" ] && [ "$(printf '%s' "$RELEASE_JSON" | jq -r '.draft')" != "true" ]; then
    die "Release $TAG is already published"
fi

TEMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/arduinoeditor-publish.XXXXXX")"
NOTES_FILE="$TEMP_DIR/release-notes.md"
CHECKSUM_FILE="$TEMP_DIR/SHA256SUMS"

(
    cd "$BUILD_DIR"
    shasum -a 256 "${ARTIFACT_NAMES[@]}"
) > "$CHECKSUM_FILE"

if [ -z "$RELEASE_JSON" ]; then
    step "Generate release notes with Codex"
    PROMPT="Write GitHub release notes in English for Arduino Editor $VERSION.
Inspect the actual git history and diff in the range $PREVIOUS_TAG..HEAD; do not rely only on commit subjects.
Describe only user-visible changes. Omit version bumps, formatting/localization churn, release scripts, build infrastructure, and implementation details.
Use concise Markdown with only the applicable headings among: ### Added, ### Improved, ### Fixed.
Use bullet points, no title, no introduction, no Full Changelog section, and do not claim anything not supported by the diff."

    codex exec \
        --sandbox read-only \
        --ephemeral \
        --color never \
        --cd "$REPO_DIR" \
        --output-last-message "$NOTES_FILE" \
        "$PROMPT"

    require_file "$NOTES_FILE"
    grep -Eq '^### (Added|Improved|Fixed)$' "$NOTES_FILE" ||
        die "Codex output does not contain an expected release-notes heading"
    cat >> "$NOTES_FILE" <<EOF

### Full Changelog

* [$PREVIOUS_TAG...$TAG](https://github.com/$REPO_SLUG/compare/$PREVIOUS_TAG...$TAG)
EOF
fi

if [ "$DRY_RUN" -eq 1 ]; then
    step "Dry-run release summary"
    echo "Tag:       $TAG"
    echo "Commit:    $COMMIT"
    echo "Previous:  $PREVIOUS_TAG"
    echo "Artifacts: ${#ARTIFACTS[@]} packages plus SHA256SUMS"
    if [ -n "$RELEASE_JSON" ]; then
        echo "Draft:     $(printf '%s' "$RELEASE_JSON" | jq -r '.html_url')"
        echo "Notes:     existing draft notes would be preserved"
    else
        echo
        cat "$NOTES_FILE"
    fi
    echo
    cat "$CHECKSUM_FILE"
    exit 0
fi

step "Prepare tag $TAG"
if ! git rev-parse --verify --quiet "refs/tags/$TAG" >/dev/null; then
    git tag -a "$TAG" -m "$TITLE" "$COMMIT"
fi
if [ -z "$REMOTE_TAG_COMMIT" ]; then
    git push origin "refs/tags/$TAG"
fi

if [ -z "$RELEASE_JSON" ]; then
    step "Create draft GitHub Release"
    gh release create "$TAG" \
        --repo "$REPO_SLUG" \
        --draft \
        --latest=false \
        --verify-tag \
        --title "$TITLE" \
        --notes-file "$NOTES_FILE" \
        "${ARTIFACTS[@]}" \
        "$CHECKSUM_FILE"
else
    step "Resume existing draft upload"
    UPLOADS=()
    ALL_UPLOADS=("${ARTIFACTS[@]}" "$CHECKSUM_FILE")
    for path in "${ALL_UPLOADS[@]}"; do
        name="$(basename "$path")"
        local_size="$(file_size "$path")"
        remote_size="$(printf '%s' "$RELEASE_JSON" | jq -r --arg name "$name" '.assets[]? | select(.name == $name) | .size' | head -n 1)"
        if [ -z "$remote_size" ]; then
            UPLOADS+=("$path")
        elif [ "$remote_size" != "$local_size" ]; then
            die "Draft asset $name exists with a different size; refusing to overwrite it"
        fi
    done
    if [ "${#UPLOADS[@]}" -gt 0 ]; then
        gh release upload "$TAG" --repo "$REPO_SLUG" "${UPLOADS[@]}"
    fi
fi

RELEASE_URL="$(gh release view "$TAG" --repo "$REPO_SLUG" --json url --jq '.url')"
step "Draft $TAG is ready"
echo "$RELEASE_URL"
echo
echo "After reviewing the draft, publish it with:"
echo "  gh release edit $TAG --repo $REPO_SLUG --draft=false --latest"
