#pragma once

#include <deque>
#include <string>
#include <utility>
#include <vector>

class ArduinoPlotView;

struct BufferedPlotLine {
  std::string line;
  double time;
};

class ArduinoPlotParser {
public:
  explicit ArduinoPlotParser(ArduinoPlotView *view);

  // Feed one serial line (UTF-8 expected). Stateful autodetection.
  void ApplyLine(const std::string &line, double time);
  void ApplyBatch(const std::vector<BufferedPlotLine> &lines);

  void Reset();

  // Optional knobs (defaults are sane)
  void SetAcceptDecimalComma(bool enabled) { m_acceptDecimalCommaUser = enabled; }
  void SetMaxProbeLines(size_t n) { m_maxProbeLines = (n < 1 ? 1 : n); }
  void SetStrictStart(bool enabled) { m_strictStart = enabled; } // if true: do not plot until mode is decided

private:
  enum class Mode {
    Unknown,
    Tagged, // name=value, name:value, or implicit name value pairs
    Columns // numeric columns (CSV/space/semicolon); optional header
  };

  struct ProbeLine {
    std::string raw;
  };

  // Main decision helpers
  void ProcessLine_Unknown(const std::string &line);
  void ProcessLine_Tagged(const std::string &line);
  void ProcessLine_Columns(const std::string &line);

  void DecideModeFromProbe();
  void FlushProbeAsCurrentMode();

  // Parsing primitives
  static bool IsLikelyHeaderLine(const std::string &line, std::vector<std::string> &outNames);
  static bool LooksLikeIdentifier(const std::string &tok);
  static bool HasAnyDigit(const std::string &s);
  static bool HasLetter(const std::string &s);

  static std::vector<std::string> SplitTokensLoose(const std::string &line);
  static std::vector<std::string> SplitTokensByDelims(const std::string &line, const char *delims);

  static bool ParseNumberPrefix(const std::string &tok, bool acceptCommaDecimal, double &out);
  static bool HeuristicAcceptCommaDecimal(const std::string &line);

  static size_t ParseTaggedPairs(const std::string &line,
                                 bool acceptCommaDecimal,
                                 std::vector<std::pair<std::string, double>> &out);
  static size_t ParseImplicitPairs(const std::vector<std::string> &toks,
                                   bool acceptCommaDecimal,
                                   std::vector<std::pair<std::string, double>> &out);
  static size_t ParseColumns(const std::string &line,
                             bool acceptCommaDecimal,
                             std::vector<double> &outValues,
                             char &outDelimiterHint);

  // Output
  void EmitSample(const std::string &name, double value);
  void EmitColumns(const std::vector<double> &values);

private:
  ArduinoPlotView *m_view = nullptr;

  Mode m_mode = Mode::Unknown;

  double m_time;

  // Probe/buffering while in Unknown (so we can start plotting only after confidence)
  std::deque<ProbeLine> m_probe;
  size_t m_maxProbeLines = 6;

  // Columns-mode names (from header or autogenerated v0..)
  std::vector<std::string> m_columnNames;
  std::vector<std::string> m_pendingHeaderNames; // detected header before mode lock
  int m_lastColumnCount = 0;

  // Settings
  bool m_acceptDecimalCommaUser = false; // explicit user preference (off by default)
  bool m_strictStart = true;             // start plotting only after mode decided

  // Minor state: last delimiter hint in columns mode
  char m_columnsDelimHint = '\0';
};
