#include "ard_ev.hpp"

wxDEFINE_EVENT(EVT_CLANG_ARGS_READY, wxThreadEvent);

wxDEFINE_EVENT(EVT_COMPLETION_READY, wxThreadEvent);

wxDEFINE_EVENT(EVT_DIAGNOSTICS_UPDATED, wxThreadEvent);

wxDEFINE_EVENT(EVT_COMMANDLINE_OUTPUT_MSG, wxCommandEvent);

wxDEFINE_EVENT(EVT_LIBRARIES_UPDATED, wxThreadEvent);

wxDEFINE_EVENT(EVT_INSTALLED_LIBRARIES_UPDATED, wxThreadEvent);

wxDEFINE_EVENT(EVT_CORES_UPDATED, wxThreadEvent);

wxDEFINE_EVENT(EVT_CORES_LOADED, wxThreadEvent);

wxDEFINE_EVENT(wxEVT_SERIAL_MONITOR_DATA, wxThreadEvent);

wxDEFINE_EVENT(wxEVT_SERIAL_MONITOR_ERROR, wxThreadEvent);

wxDEFINE_EVENT(EVT_BOARD_OPTIONS_READY, wxThreadEvent);

wxDEFINE_EVENT(EVT_AVAILABLE_BOARDS_UPDATED, wxThreadEvent);

wxDEFINE_EVENT(EVT_PROGRAMMERS_READY, wxThreadEvent);

wxDEFINE_EVENT(EVT_RESOLVED_LIBRARIES_READY, wxThreadEvent);

wxDEFINE_EVENT(EVT_SYMBOL_OCCURRENCES_READY, wxThreadEvent);

wxDEFINE_EVENT(wxEVT_AI_SIMPLE_CHAT_SUCCESS, wxThreadEvent);

wxDEFINE_EVENT(wxEVT_AI_SIMPLE_CHAT_ERROR, wxThreadEvent);

wxDEFINE_EVENT(wxEVT_AI_SIMPLE_CHAT_PROGRESS, wxThreadEvent);

wxDEFINE_EVENT(wxEVT_AI_SUMMARIZATION_UPDATED, wxThreadEvent);

wxDEFINE_EVENT(EVT_STOP_PROCESS, wxThreadEvent);

wxDEFINE_EVENT(EVT_SYMBOL_USAGES_READY, wxThreadEvent);
